apiVersion: v1
description: Bookinfo details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student89/details
maintainers:
  - name: student89
    email: devop89@mail.kmutt.ac.th
sources:
  - https://github.com/fxxhhhhhhh/bookinfo-details